title:            Axu Blog
description:      get busy living,or get busy dying.
disqus_shortname: xuguojing                            # disqus_comments
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
<<<<<<< HEAD
#url:              #http://huangxubo.me/blog
=======
#11url:              #http://huangxubo.me/blog
>>>>>>> a3a5b0dd78d0dcf5444644b08b5ef967413e8269

home_url:         https://axu666.win

post_img:
  feature: abstract-1.jpg
  credit: snow
  creditlink: snow

# Owner/author information
owner:
  name:           mraxu
  avatar:         avatar.jpg
  bio:            "Your bio Ygoes here. It shouldn't be super long but a good sentence or two should suffice."
  email:          gj-x@qq.com
  # Social networking links used in footer. Update and remove as you like.
  weibo:          http://weibo.com
  wechat:         vvvvvvgj
  douban:
  zhihu:
  stackoverflow:  https://stackoverflow.com/users/9692767/axu
  twitter:        https://twitter.com/HeartNoBNumber
  facebook:
  github:         https://github.com/
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# SEO
seo:
  title:  IT博客,Linux,Centos,RetHat,RAID
  description: 服务器技术博客,核心IT技术包括：Linux,Windows Server,RAID

# Background image to be tiled on all pages
background:

background_color: F7F7F7

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 61e6a4d794b0d024d935a5266c22ef04
# Analytics and webmaster tools stuff goes here
google_analytics: UA-110582355-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown
# Markdown解析插件rdiscount,kramdown,redcarpet

# redcarpet:
#   extensions: [with_toc_data]

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  input: GFM
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
#  use_coderay: true
#  enable_coderay: false

#  coderay:
#    coderay_line_numbers: nil
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true
# aside 控制aside显示隐藏时，需修改_page.scss中的#post-index中mian的max-width宽度
aside : true

#导航栏
pages_list:
  Blog: ''
  Categories: 'categories'
  Archives: 'posts'
#  SiteMap: 'sitemap'
#  Contact: 'contact'
  About: 'about'

include: [".htaccess"]
exclude: ["note","Timeline","lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
# 文章分类
# category: developer,life
